{"name": "test_login_with_invalid_credentials", "status": "passed", "description": "Логин с неверным логином и паролем", "start": 1719430384871, "stop": 1719430385077, "uuid": "dee8fcd5-f54c-4d5c-9ec2-218314c14943", "historyId": "2398d9cdaab9063fe5c0130bb3197e44", "testCaseId": "2398d9cdaab9063fe5c0130bb3197e44", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4LHP98R"}, {"name": "thread", "value": "23504-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}