{"name": "test_create_duplicate_user", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <allure_commons._allure.fixture object at 0x000002005DE402F0>, args = (), kwargs = {}\n\n    def __call__(self, *args, **kwargs):\n        self.parameters = func_parameters(self._fixture_function, *args, **kwargs)\n    \n        with self:\n>           return self._fixture_function(*args, **kwargs)\n\n.venv\\Lib\\site-packages\\allure_commons\\_allure.py:221: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    @pytest.fixture(scope='function')\n    def data_new3():\n        payload = helper.CreateCurrierData().generate_currier_data()\n        response_create_user = requests.post(urls.BASE_URL + urls.AUTH_REGISTER_USER_URL, data=payload)\n        yield response_create_user, payload\n>       token = response_create_user.json()[\"accessToken\"]\nE       KeyError: 'accessToken'\n\nconftest.py:12: KeyError"}, "description": "Создание пользователя, который уже зарегистрирован", "start": 1719430255282, "stop": 1719430255812, "uuid": "5d061f02-7e9c-4ceb-ad2e-8924524f1f62", "historyId": "6d52ca1a018cd3a9c525cfafef02b1e9", "testCaseId": "6d52ca1a018cd3a9c525cfafef02b1e9", "fullName": "tests.test_create_user.TestCreateUser#test_create_duplicate_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-4LHP98R"}, {"name": "thread", "value": "19696-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}