{"name": "test_login_with_invalid_credentials", "status": "passed", "description": "Логин с неверным логином и паролем", "start": 1719430168733, "stop": 1719430168968, "uuid": "f18d03dc-8b5e-4712-958d-e1cc7f9e7e2d", "historyId": "2398d9cdaab9063fe5c0130bb3197e44", "testCaseId": "2398d9cdaab9063fe5c0130bb3197e44", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4LHP98R"}, {"name": "thread", "value": "24376-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}