{"name": "test_login_with_invalid_credentials", "status": "passed", "description": "Логин с неверным логином и паролем", "start": 1719429922598, "stop": 1719429922705, "uuid": "b6ec843c-a4b1-49fe-b01f-12955b0b618d", "historyId": "2398d9cdaab9063fe5c0130bb3197e44", "testCaseId": "2398d9cdaab9063fe5c0130bb3197e44", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4LHP98R"}, {"name": "thread", "value": "14636-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}