{"name": "test_login_with_invalid_credentials", "status": "passed", "description": "Логин с неверным логином и паролем", "start": 1719429899211, "stop": 1719429899320, "uuid": "ad671dfc-7e60-47de-8ac9-d06750b892a4", "historyId": "2398d9cdaab9063fe5c0130bb3197e44", "testCaseId": "2398d9cdaab9063fe5c0130bb3197e44", "fullName": "tests.test_login_user.TestLoginUser#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-4LHP98R"}, {"name": "thread", "value": "14364-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}